services:
  - type: web
    name: comedk-predictor
    env: python
    buildCommand: pip install -r requirements.txt && python setup_db.py
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
